id: I4BC94AF6
ocr_import_info:
  timestamp: '2023-07-26T13:08:33.772931+00:00'
  batch_id: batch-6331
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/latest
  ocr_lang_hint: bo
  software_id: ocr-pipelines@v0.1.11
  sponsor: DS
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-07-26 14:14:37.131621+00:00
last_modified: 2023-07-26 14:14:37.131629+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4277
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4277
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་འབྲུག་པའི་ཟབ་ཁྲིད་ཕྱོགས་བསྡེབས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.3591252894089924
  ocr_word_median_confidence_index: 0.32427225000000004
bases:
  I1PD100452:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100452
      total_pages: 624
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1PD100452.txt
    statistics:
      ocr_word_median_confidence_index: 0.32635796
      ocr_word_mean_confidence_index: 0.36423453641086145
  I1PD100451:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100451
      total_pages: 616
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1PD100451.txt
    statistics:
      ocr_word_median_confidence_index: 0.32636037
      ocr_word_mean_confidence_index: 0.3623523899123299
  I1PD100450:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100450
      total_pages: 672
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD100450.txt
    statistics:
      ocr_word_median_confidence_index: 0.31749499999999997
      ocr_word_mean_confidence_index: 0.34674327163800317
  I1PD100453:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100453
      total_pages: 608
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1PD100453.txt
    statistics:
      ocr_word_median_confidence_index: 0.32504982
      ocr_word_mean_confidence_index: 0.35923837847506684
  I1PD100449:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD100449
      total_pages: 668
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD100449.txt
    statistics:
      ocr_word_median_confidence_index: 0.32586327
      ocr_word_mean_confidence_index: 0.3650599455363225
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
